#include <iostream> // IWYU pragma: keep
					// Used by EXPECT_ macros to print results

#if defined(__clang__)
#define TEST_COMPILER_CLANG

#elif defined(__GNUC__) || defined(__GNUG__)
#define TEST_COMPILER_GCC

#elif defined(_MSC_VER)
#define TEST_COMPILER_MSVC

#endif

#if defined(TEST_COMPILER_CLANG)
#define Test_ForceInline inline __attribute__((always_inline))
#define Test_AlignOf(type) __alignof__(type)

#define Test_PushPack
#define Test_PopPack __attribute__((__packed__))

#define Test_Unreachable __builtin_unreachable()

#define Test_FUNCTION_ __func__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#elif defined(TEST_COMPILER_GCC)
#define Test_ForceInline inline __attribute__((always_inline))
#define Test_AlignOf(type) __alignof__(type)

#define Test_PushPack
#define Test_PopPack __attribute__((__packed__))

#define Test_Unreachable __builtin_unreachable()

#define Test_FUNCTION_ __func__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#elif defined(TEST_COMPILER_MSVC)
#define Test_ForceInline __forceinline
#define Test_AlignOf(type) alignof(type)

#define Test_PushPack __pragma(pack(push, 1))
#define Test_PopPack __pragma(pack(pop))

#define Test_Unreachable __assume(0)

#define Test_FUNCTION_ __FUNCTION__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#endif

/*
 * Warning pragmas
 */
#ifdef TEST_COMPILER_CLANG
#define TEST_PRAGMA(x) _Pragma(#x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(clang diagnostic push)
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(clang diagnostic pop)
#define TEST_CLANG_SUPPRESS_WARNING(w) TEST_PRAGMA(clang diagnostic ignored w)
#if __clang_major__ >= 13
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w) TEST_CLANG_SUPPRESS_WARNING(w)
#else
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w)
#endif
#if __clang_major__ >= 16
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w) TEST_CLANG_SUPPRESS_WARNING(w)
#else
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w)
#endif
#else
#define TEST_CLANG_SUPPRESS_WARNING(w)
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w)
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w)
#endif
#ifdef TEST_COMPILER_GCC
#define TEST_PRAGMA(x) _Pragma(#x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(GCC diagnostic push)
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(GCC diagnostic pop)
#define TEST_GCC_SUPPRESS_WARNING(w) TEST_PRAGMA(GCC diagnostic ignored w)
#else
#define TEST_GCC_SUPPRESS_WARNING(w)
#endif
#ifdef TEST_COMPILER_MSVC
#define TEST_PRAGMA(x) __pragma(x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(warning(push))
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(warning(pop))
#define TEST_MSVC_SUPPRESS_WARNING(w) TEST_PRAGMA(warning(disable : w))
#if _MSC_VER >= 1920 && _MSC_VER < 1930
#define TEST_MSVC2019_SUPPRESS_WARNING(w) TEST_MSVC_SUPPRESS_WARNING(w)
#else
#define TEST_MSVC2019_SUPPRESS_WARNING(w)
#endif
#else
#define TEST_MSVC_SUPPRESS_WARNING(w)
#define TEST_MSVC2019_SUPPRESS_WARNING(w)
#endif

/*
 * Disable common warnings when using -Wall
 *
 * TODO(randomuserhi): Check GCC & Clang warnings
 * TODO(randomuserhi): Check which ones I actually need ...
 */
#define TEST_SUPPRESS_WARNINGS TEST_CLANG_SUPPRESS_WARNING("-Wglobal-constructors")

TEST_SUPPRESS_WARNING_PUSH
TEST_SUPPRESS_WARNINGS

// Suppress warnings generated by the standard template library
#define TEST_SUPPRESS_WARNINGS_STD_BEGIN TEST_SUPPRESS_WARNING_PUSH

#define TEST_SUPPRESS_WARNINGS_STD_END TEST_SUPPRESS_WARNING_POP

// Stringifies its argument.
// Work around a bug in visual studio which doesn't accept code like this:
//
//   #define TEST_STRINGIFY_(name) #name
//   #define MACRO(a, b, c) ... TEST_STRINGIFY_(a) ...
//   MACRO(, x, y)
//
// Complaining about the argument to TEST_STRINGIFY_ being empty.
// This is allowed by the spec.
#define TEST_STRINGIFY_HELPER_(name, ...) #name
#define TEST_STRINGIFY_(...) TEST_STRINGIFY_HELPER_(__VA_ARGS__, )

#define TEST_CLASSNAME_(group, name) TEST_CLASS_##group##_##name
#define TEST_CLASSNAME_INFO(group, name) TEST_CLASS_##group##_##name##_INFO

#define EXPECT_EQ(a, b)                                                                                                     \
	do {                                                                                                                    \
		if ((a) != (b)) {                                                                                                   \
			Test::internal::g_testFailed = true;                                                                            \
			std::cout << "\n\tEquality between " << #a << " and " << #b << " failed\n\t - " << Test_FILE_                   \
					  << " (ln: " << Test_LINE_ << ")";                                                                     \
		}                                                                                                                   \
	} while (0)
#define EXPECT_NE(a, b)                                                                                                     \
	do {                                                                                                                    \
		if ((a) == (b)) {                                                                                                   \
			Test::internal::g_testFailed = true;                                                                            \
			std::cout << "\n\tInequality between " << #a << " and " << #b << " failed";                                     \
		}                                                                                                                   \
	} while (0)

#define EXPECT_TRUE(condition)                                                                                              \
	do {                                                                                                                    \
		if (!(condition)) {                                                                                                 \
			Test::internal::g_testFailed = true;                                                                            \
			std::cout << "\n\tCondition '" << #condition << "' was false, but expected true.";                              \
		}                                                                                                                   \
	} while (0)
#define EXPECT_FALSE(condition)                                                                                             \
	do {                                                                                                                    \
		if ((condition)) {                                                                                                  \
			Test::internal::g_testFailed = true;                                                                            \
			std::cout << "\n\tCondition '" << #condition << "' was true, but expected false.";                              \
		}                                                                                                                   \
	} while (0)

namespace Test {

TEST_SUPPRESS_WARNING_PUSH
TEST_CLANG_SUPPRESS_WARNING("-Wpadded")
class TestBase {
protected:
	virtual ~TestBase();

public:
	virtual void TestBody() const = 0;

	TestBase() = default;
	TestBase(const TestBase&) = delete;
};
TEST_SUPPRESS_WARNING_POP

struct TestInfo {
	int m_line;
	const TestBase* m_testObj;
	const char* m_testGroup;
	const char* m_testName;
	const char* m_file;

	inline TestInfo(const char* roTestGroup, const char* roTestName, const char* roFile, int roLine,
	                const TestBase* roTestObj) :
		m_line(roLine), m_testObj(roTestObj), m_testGroup(roTestGroup), m_testName(roTestName), m_file(roFile) {}
};

const TestInfo* RegisterTest(const char* roTestGroup, const char* roTestName, const char* roFile, int roLine,
                             const TestBase* roTestObj);

namespace internal {

extern bool g_testFailed;

} // namespace internal

int RunAllTests();

} // namespace Test

#define TEST(testGroup, testName)                                                                                           \
	static_assert(sizeof(TEST_STRINGIFY_(testGroup)) > 1, "Test name must not be empty");                                   \
	static_assert(sizeof(TEST_STRINGIFY_(testName)) > 1, "Test name must not be empty");                                    \
	TEST_SUPPRESS_WARNING_PUSH                                                                                              \
	TEST_SUPPRESS_WARNINGS                                                                                                  \
	class TEST_CLASSNAME_(testGroup, testName) :                                                                            \
		public Test::TestBase {                                                                                             \
	public:                                                                                                                 \
		void TestBody() const final override;                                                                               \
		TEST_CLASSNAME_(testGroup, testName)() = default;                                                                   \
		TEST_CLASSNAME_(testGroup, testName)(TEST_CLASSNAME_(testGroup, testName) &) = delete;                              \
		~TEST_CLASSNAME_(testGroup, testName)() override = default;                                                         \
	};                                                                                                                      \
	const Test::TestInfo* const TEST_CLASSNAME_INFO(testGroup, testName) =                                                  \
		Test::RegisterTest(#testGroup, #testName, Test_FILE_, Test_LINE_, new TEST_CLASSNAME_(testGroup, testName)());      \
	TEST_SUPPRESS_WARNING_POP                                                                                               \
	void TEST_CLASSNAME_(testGroup, testName)::TestBody() const

TEST_SUPPRESS_WARNING_POP
