#include <iostream> // IWYU pragma: export
#include <string>
#include <chrono>

// TODO(randomuserhi): Benchmarking lib to support proper benchmkars (timings are mostly just how long it took to execute the
//                     test)

#if defined(__clang__)
#define TEST_COMPILER_CLANG

#elif defined(__GNUC__) || defined(__GNUG__)
#define TEST_COMPILER_GCC

#elif defined(_MSC_VER)
#define TEST_COMPILER_MSVC

#endif

#if defined(TEST_COMPILER_CLANG)
#define Test_ForceInline inline __attribute__((always_inline))
#define Test_AlignOf(type) __alignof__(type)

#define Test_PushPack
#define Test_PopPack __attribute__((__packed__))

#define Test_Unreachable __builtin_unreachable()

#define Test_FUNCTION_ __func__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#elif defined(TEST_COMPILER_GCC)
#define Test_ForceInline inline __attribute__((always_inline))
#define Test_AlignOf(type) __alignof__(type)

#define Test_PushPack
#define Test_PopPack __attribute__((__packed__))

#define Test_Unreachable __builtin_unreachable()

#define Test_FUNCTION_ __func__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#elif defined(TEST_COMPILER_MSVC)
#define Test_ForceInline __forceinline
#define Test_AlignOf(type) alignof(type)

#define Test_PushPack __pragma(pack(push, 1))
#define Test_PopPack __pragma(pack(pop))

#define Test_Unreachable __assume(0)

#define Test_FUNCTION_ __FUNCTION__
#define Test_FILE_ __FILE__
#define Test_LINE_ __LINE__

#endif

/*
 * Warning pragmas
 */
#ifdef TEST_COMPILER_CLANG
#define TEST_PRAGMA(x) _Pragma(#x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(clang diagnostic push)
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(clang diagnostic pop)
#define TEST_CLANG_SUPPRESS_WARNING(w) TEST_PRAGMA(clang diagnostic ignored w)
#if __clang_major__ >= 13
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w) TEST_CLANG_SUPPRESS_WARNING(w)
#else
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w)
#endif
#if __clang_major__ >= 16
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w) TEST_CLANG_SUPPRESS_WARNING(w)
#else
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w)
#endif
#else
#define TEST_CLANG_SUPPRESS_WARNING(w)
#define TEST_CLANG_13_PLUS_SUPPRESS_WARNING(w)
#define TEST_CLANG_16_PLUS_SUPPRESS_WARNING(w)
#endif
#ifdef TEST_COMPILER_GCC
#define TEST_PRAGMA(x) _Pragma(#x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(GCC diagnostic push)
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(GCC diagnostic pop)
#define TEST_GCC_SUPPRESS_WARNING(w) TEST_PRAGMA(GCC diagnostic ignored w)
#else
#define TEST_GCC_SUPPRESS_WARNING(w)
#endif
#ifdef TEST_COMPILER_MSVC
#define TEST_PRAGMA(x) __pragma(x)
#define TEST_SUPPRESS_WARNING_PUSH TEST_PRAGMA(warning(push))
#define TEST_SUPPRESS_WARNING_POP TEST_PRAGMA(warning(pop))
#define TEST_MSVC_SUPPRESS_WARNING(w) TEST_PRAGMA(warning(disable : w))
#if _MSC_VER >= 1920 && _MSC_VER < 1930
#define TEST_MSVC2019_SUPPRESS_WARNING(w) TEST_MSVC_SUPPRESS_WARNING(w)
#else
#define TEST_MSVC2019_SUPPRESS_WARNING(w)
#endif
#else
#define TEST_MSVC_SUPPRESS_WARNING(w)
#define TEST_MSVC2019_SUPPRESS_WARNING(w)
#endif

/*
 * Disable common warnings when using -Wall
 *
 * TODO(randomuserhi): Check GCC & Clang warnings
 * TODO(randomuserhi): Check which ones I actually need ...
 */
#define TEST_SUPPRESS_WARNINGS TEST_CLANG_SUPPRESS_WARNING("-Wglobal-constructors")

TEST_SUPPRESS_WARNING_PUSH
TEST_SUPPRESS_WARNINGS

// Suppress warnings generated by the standard template library
#define TEST_SUPPRESS_WARNINGS_STD_BEGIN TEST_SUPPRESS_WARNING_PUSH

#define TEST_SUPPRESS_WARNINGS_STD_END TEST_SUPPRESS_WARNING_POP

// Stringifies its argument.
// Work around a bug in visual studio which doesn't accept code like this:
//
//   #define TEST_STRINGIFY_(name) #name
//   #define MACRO(a, b, c) ... TEST_STRINGIFY_(a) ...
//   MACRO(, x, y)
//
// Complaining about the argument to TEST_STRINGIFY_ being empty.
// This is allowed by the spec.
#define TEST_STRINGIFY_HELPER_(in_name, ...) #in_name
#define TEST_STRINGIFY_(...) TEST_STRINGIFY_HELPER_(__VA_ARGS__, )

#define TEST_CLASSNAME_(in_group, in_name) TEST_CLASS_##in_group##_##in_name
#define TEST_CLASSNAME_INFO(in_group, in_name) TEST_CLASS_##in_group##_##in_name##_INFO

#define TEST_CASENAME_(in_caseName) TEST_CASE_##in_caseName

#define EXPECT_EQ(a, b)                                                                                                     \
	do {                                                                                                                    \
		if ((a) != (b)) {                                                                                                   \
			this->m_failed = true;                                                                                          \
			this->Indent();                                                                                                 \
			*this->m_out += "\tEquality between " #a " and " #b " failed";                                                  \
			this->Indent();                                                                                                 \
			*this->m_out += "\t - " TEST_STRINGIFY_(Test_FILE_) " (ln: " TEST_STRINGIFY_(Test_LINE_) ")";                   \
		}                                                                                                                   \
	} while (0)
#define EXPECT_NE(a, b)                                                                                                     \
	do {                                                                                                                    \
		if ((a) == (b)) {                                                                                                   \
			this->m_failed = true;                                                                                          \
			this->Indent();                                                                                                 \
			*this->m_out += "\tInequality between " #a " and " #b " failed";                                                \
			this->Indent();                                                                                                 \
			*this->m_out += "\t - " TEST_STRINGIFY_(Test_FILE_) " (ln: " TEST_STRINGIFY_(Test_LINE_) ")";                   \
		}                                                                                                                   \
	} while (0)

#define EXPECT_TRUE(condition)                                                                                              \
	do {                                                                                                                    \
		if (!(condition)) {                                                                                                 \
			this->m_failed = true;                                                                                          \
			this->Indent();                                                                                                 \
			*this->m_out += "\tCondition '" #condition "' was false, but expected true";                                    \
			this->Indent();                                                                                                 \
			*this->m_out += "\t - " TEST_STRINGIFY_(Test_FILE_) " (ln: " TEST_STRINGIFY_(Test_LINE_) ")";                   \
		}                                                                                                                   \
	} while (0)
#define EXPECT_FALSE(condition)                                                                                             \
	do {                                                                                                                    \
		if ((condition)) {                                                                                                  \
			this->m_failed = true;                                                                                          \
			this->Indent();                                                                                                 \
			*this->m_out += "\tCondition '" #condition "' was true, but expected false";                                    \
			this->Indent();                                                                                                 \
			*this->m_out += "\t - " TEST_STRINGIFY_(Test_FILE_) " (ln: " TEST_STRINGIFY_(Test_LINE_) ")";                   \
		}                                                                                                                   \
	} while (0)

namespace Test {

TEST_SUPPRESS_WARNING_PUSH
TEST_CLANG_SUPPRESS_WARNING("-Wpadded")
class TestBase {
public:
	virtual void TestBody() = 0;

	TestBase() = default;
	TestBase(const TestBase&) = delete;

	// Initializes the test
	void Init();

	// Writes indentation to the output string based on `m_depth`
	void Indent(bool in_newLine = true);

	std::string m_buf;
	std::string* m_out = &m_buf;
	size_t m_depth = 1;
	bool m_failed = false;

protected:
	virtual ~TestBase() = default;
};
TEST_SUPPRESS_WARNING_POP

class TestCase {
public:
	TestCase(const char* in_caseName, TestBase& in_testObj);
	~TestCase();

	const char* m_caseName;

	// Owning Test Object
	TestBase& m_testObj;

	// Previous out buffer to write messages to
	std::string* m_out;

	// Current out buffer messages get written to whilst within this case
	std::string m_buf;

	bool m_hasRun = false;

private:
	using TimePoint = decltype(std::chrono::high_resolution_clock::now());

	TimePoint m_start;
	TimePoint m_end;
};

struct TestInfo {
	int m_line;
	TestBase* m_testObj;
	const char* m_testGroup;
	const char* m_testName;
	const char* m_file;

	inline TestInfo(const char* in_testGroup, const char* in_testName, const char* in_file, int in_line,
	                TestBase* in_testObj) :
		m_line(in_line), m_testObj(in_testObj), m_testGroup(in_testGroup), m_testName(in_testName), m_file(in_file) {}
};

const TestInfo* RegisterTest(const char* in_testGroup, const char* in_testName, const char* in_file, int in_lLine,
                             TestBase* in_testObj);

int RunAllTests();

} // namespace Test

#define TEST(in_testGroup, in_testName)                                                                                     \
	static_assert(sizeof(TEST_STRINGIFY_(in_testGroup)) > 1, "Test name must not be empty");                                \
	static_assert(sizeof(TEST_STRINGIFY_(in_testName)) > 1, "Test name must not be empty");                                 \
	TEST_SUPPRESS_WARNING_PUSH                                                                                              \
	TEST_SUPPRESS_WARNINGS                                                                                                  \
	class TEST_CLASSNAME_(in_testGroup, in_testName) :                                                                      \
		public Test::TestBase {                                                                                             \
	public:                                                                                                                 \
		void TestBody() final override;                                                                                     \
		TEST_CLASSNAME_(in_testGroup, in_testName)() = default;                                                             \
		TEST_CLASSNAME_(in_testGroup, in_testName)(TEST_CLASSNAME_(in_testGroup, in_testName) &) = delete;                  \
		~TEST_CLASSNAME_(in_testGroup, in_testName)() override = default;                                                   \
	};                                                                                                                      \
	const Test::TestInfo* const TEST_CLASSNAME_INFO(in_testGroup, in_testName) = Test::RegisterTest(                        \
		#in_testGroup, #in_testName, Test_FILE_, Test_LINE_, new TEST_CLASSNAME_(in_testGroup, in_testName)());             \
	TEST_SUPPRESS_WARNING_POP                                                                                               \
	void TEST_CLASSNAME_(in_testGroup, in_testName)::TestBody()

#define TEST_CASE(in_caseName)                                                                                              \
	for (::Test::TestCase TEST_CASENAME_(in_caseName){ #in_caseName, *this }; !TEST_CASENAME_(in_caseName).m_hasRun;        \
	     TEST_CASENAME_(in_caseName).m_hasRun = true)

TEST_SUPPRESS_WARNING_POP
